# -*- coding: utf-8 -*-
"""wrongWordGenerator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kdu5JbwM4Az70DWo1i8Qd-aVa4OqME0I
"""



import pandas as pd
from bltk.langtools.banglachars import (vowels,
                                        vowel_signs,
                                        consonants,
                                        digits,
                                        operators,
                                        punctuations,
                                        others)
#
# from google.colab import drive
# drive.mount('/content/drive')

data = pd.read_excel("D:\Python\Context Based Spell Checker using RNN\Processings\Data\combined-unique.xlsx")
vocabs = data['wordList']

def split(words):
  return [ (words[:i], words[i:]) for i in range(len(words) + 1)]

print(split("নিয়েছেন"))

def delete(word):
  return [l + r[1:] for l,r in split(word) if r]

print(delete("নিয়েছেন"))

def swap(word):
  return [l + r[1] + r[0] + r[2:] for l,r in split(word) if len(r)>1]

print(swap("নিয়েছেন"))

def replace(word):
  letters = []
  for i in vowels:
    letters.append(i)

  for i in vowel_signs:
    letters.append(i)
    
  for i in consonants:
    letters.append(i)
  
  for i in range(0,5):
    letters.append(others[i])
  return [l + c + r[1:] for l,r in split(word) if r for c in letters]

print(replace("নিয়েছেন"))

def insert(word):
  letters = []
  for i in vowels:
    letters.append(i)

  for i in vowel_signs:
    letters.append(i)
    
  for i in consonants:
    letters.append(i)
  
  for i in range(0,5):
    letters.append(others[i])
  
  return [l + c + r for l,r in split(word) for c in letters]

print(insert("নিয়েছেন"))

def level_one_edit(word):
  return set(delete(word) + swap(word) + replace(word) + insert(word))

def level_two_edit(word):
  return set(e2 for e1 in level_one_edit(word) for e2 in level_one_edit(e1))

def wrong_words(word, vocabulary):
  if word in vocabulary:
    print(f"(word) is already correctly spelt")
    return
  
  suggestion = level_one_edit(word) or level_two_edit(word) or [word]
  return  [w for w in suggestion if w not in vocabulary]

word = "নিয়েছন"
guesses = wrong_words(word, vocabs)

print(guesses)

wordList = []
count = 0
cc = 0
for word in vocabs:
  ls = wrong_words(word, vocabs)
  wordList = wordList + ls
  if(len(wordList)>200000):
    wordList = set(wordList)
    df = pd.DataFrame(wordList)
    df.columns = ['wordList']
    loc = "D:\Python\Context Based Spell Checker using RNN\Processings\Data Extracted\Collections Of Wrong Word\ewWrongWords{0}.xlsx".format(cc)
    df.to_excel(loc,index=False)
    wordList = []
    cc += 1

  print(count)
  count +=1

print(len(wordList))

df = pd.DataFrame(wordList)
df.columns = ['wordList']
df.to_csv("D:\Python\Context Based Spell Checker using RNN\Processings\Data Extracted\ewWrongWords.csv", index=False)

print(wordList[:10])

print(len(wordList))

t1 = ['রাত্ৎরি', 'রাত্ওি', 'রাতম্রি' ]

t2 = ['রাত্ৎরি', 'রাত্ওি', 'রাতম্রি','রাতূরি', 'রাত্ছরি', 'রাত্রবি', 'রাতঃরি' ]
t3 = list(set(t1 + t2))
print(t3)